# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b6553a89b5bcf93914b479b622ac963c76f360e920e28bf30c18e4a6ec24f6dabbac59be6966b4d6e5b075bf52721d6a002438e45304a8ad99c6a5684da68d4

test:
  secret_key_base: 73bd6318850e1a7479add2db024e5592d4adb2f577536a3c50fbc1e9005d625e9bf7fb94bb7b2a619c376d8f552eab83f393ac338c836beb32929f8d56a77114

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
